//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamMocBaoWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LamMocBaoWeb.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu cần tư vấn miễn phí để dùng đá phong thuỷ hợp mệnh, bạn có thể nhắn Facebook số &lt;a href=&quot;tel:0999999999&quot;&gt;0999-999-999&lt;/a&gt; hoặc gửi thông tin bên dưới.
        /// </summary>
        public static string Advise_Contact_Messge {
            get {
                return ResourceManager.GetString("Advise_Contact_Messge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký nhận tư vấn.
        /// </summary>
        public static string Advise_Register {
            get {
                return ResourceManager.GetString("Advise_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string Appointment_Customer_Contact_Infos {
            get {
                return ResourceManager.GetString("Appointment_Customer_Contact_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin khách hàng.
        /// </summary>
        public static string Appointment_Customer_Infos {
            get {
                return ResourceManager.GetString("Appointment_Customer_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string Appointment_Customer_Name {
            get {
                return ResourceManager.GetString("Appointment_Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú khác.
        /// </summary>
        public static string Appointment_Note {
            get {
                return ResourceManager.GetString("Appointment_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn loại dịch vụ quan tâm.
        /// </summary>
        public static string Appointment_PleaseSelect_Interested_In_Service {
            get {
                return ResourceManager.GetString("Appointment_PleaseSelect_Interested_In_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm đặt lịch.
        /// </summary>
        public static string Appointment_Search_Placeholder {
            get {
                return ResourceManager.GetString("Appointment_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi liên hệ.
        /// </summary>
        public static string Appointment_Submit {
            get {
                return ResourceManager.GetString("Appointment_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã đặt lịch hẹn.
        /// </summary>
        public static string Appointment_ThankYou_To_Make_A_Appointment {
            get {
                return ResourceManager.GetString("Appointment_ThankYou_To_Make_A_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem cuộc hẹn.
        /// </summary>
        public static string Appointment_View_Appointment {
            get {
                return ResourceManager.GetString("Appointment_View_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi sẽ liên hệ bạn sớm nhất có thể hoặc nếu trong trường hợp sớm, vui lòng liên hệ qua số điện thoại {0}.
        /// </summary>
        public static string Appointment_We_Will_ContactYouASAP {
            get {
                return ResourceManager.GetString("Appointment_We_Will_ContactYouASAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch xem mệnh số với chuyên gia.
        /// </summary>
        public static string Book_date {
            get {
                return ResourceManager.GetString("Book_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string Buttons_No {
            get {
                return ResourceManager.GetString("Buttons_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string Buttons_Yes {
            get {
                return ResourceManager.GetString("Buttons_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng trống.
        /// </summary>
        public static string Cart_Empty_Inform {
            get {
                return ResourceManager.GetString("Cart_Empty_Inform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giỏ hàng.
        /// </summary>
        public static string Cart_Infos {
            get {
                return ResourceManager.GetString("Cart_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string Cart_Label {
            get {
                return ResourceManager.GetString("Cart_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại.
        /// </summary>
        public static string Cart_Type {
            get {
                return ResourceManager.GetString("Cart_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo loại sản phẩm mới.
        /// </summary>
        public static string Category_CreateNew_Category {
            get {
                return ResourceManager.GetString("Category_CreateNew_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự trong bộ lọc sản phẩm.
        /// </summary>
        public static string Category_FilterSequenceNumber {
            get {
                return ResourceManager.GetString("Category_FilterSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự ngoài trang chủ.
        /// </summary>
        public static string Category_HomePageSequenceNumber {
            get {
                return ResourceManager.GetString("Category_HomePageSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string Category_Product {
            get {
                return ResourceManager.GetString("Category_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm loại sản phẩm nào ?.
        /// </summary>
        public static string Category_Search_Placeholder {
            get {
                return ResourceManager.GetString("Category_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Category_SequenceNumber {
            get {
                return ResourceManager.GetString("Category_SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật loại sản phẩm.
        /// </summary>
        public static string Category_Update_Category {
            get {
                return ResourceManager.GetString("Category_Update_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo.
        /// </summary>
        public static string Common_Create {
            get {
                return ResourceManager.GetString("Common_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch ngay &gt;.
        /// </summary>
        public static string Common_MakeAApointment_Immediately {
            get {
                return ResourceManager.GetString("Common_MakeAApointment_Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập vào tên !.
        /// </summary>
        public static string Common_Name_IsRequired {
            get {
                return ResourceManager.GetString("Common_Name_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy {0}.
        /// </summary>
        public static string Common_No_Result {
            get {
                return ResourceManager.GetString("Common_No_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string Common_ProductPortfolio {
            get {
                return ResourceManager.GetString("Common_ProductPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại trang chủ.
        /// </summary>
        public static string Common_Return_Home_Page {
            get {
                return ResourceManager.GetString("Common_Return_Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Common_Send {
            get {
                return ResourceManager.GetString("Common_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Customer_Address {
            get {
                return ResourceManager.GetString("Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận / Huyện.
        /// </summary>
        public static string Customer_Address_District {
            get {
                return ResourceManager.GetString("Customer_Address_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Customer_Address_NumberAndStreet {
            get {
                return ResourceManager.GetString("Customer_Address_NumberAndStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh / Thành phố.
        /// </summary>
        public static string Customer_Address_Province {
            get {
                return ResourceManager.GetString("Customer_Address_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường / Xã.
        /// </summary>
        public static string Customer_Address_Ward {
            get {
                return ResourceManager.GetString("Customer_Address_Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tư vấn.
        /// </summary>
        public static string Customer_Advising {
            get {
                return ResourceManager.GetString("Customer_Advising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bao gồm các sản phẩm bạn đã quan tâm.
        /// </summary>
        public static string Customer_Advising_IncludeOtherProductsInterestedIn {
            get {
                return ResourceManager.GetString("Customer_Advising_IncludeOtherProductsInterestedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ.
        /// </summary>
        public static string Customer_Birday_Hour {
            get {
                return ResourceManager.GetString("Customer_Birday_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ tháng năm sinh.
        /// </summary>
        public static string Customer_Birthday {
            get {
                return ResourceManager.GetString("Customer_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Âm lịch.
        /// </summary>
        public static string Customer_Birthday_LunarCalendar {
            get {
                return ResourceManager.GetString("Customer_Birthday_LunarCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dương lịch.
        /// </summary>
        public static string Customer_Birthday_SolarCalendar {
            get {
                return ResourceManager.GetString("Customer_Birthday_SolarCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo ngày.
        /// </summary>
        public static string Customer_CreatedAt {
            get {
                return ResourceManager.GetString("Customer_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm muốn mua.
        /// </summary>
        public static string Customer_Desiring_Product {
            get {
                return ResourceManager.GetString("Customer_Desiring_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string Customer_Email {
            get {
                return ResourceManager.GetString("Customer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Customer_FullName {
            get {
                return ResourceManager.GetString("Customer_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung cấp thông tin để xem vận hạn năm mới.
        /// </summary>
        public static string Customer_InformBirthday_To_Receive_New_Events {
            get {
                return ResourceManager.GetString("Customer_InformBirthday_To_Receive_New_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ email.
        /// </summary>
        public static string Customer_Input_Email_PlaceHolder {
            get {
                return ResourceManager.GetString("Customer_Input_Email_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập họ và tên.
        /// </summary>
        public static string Customer_Input_FullName_PlaceHolder {
            get {
                return ResourceManager.GetString("Customer_Input_FullName_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại.
        /// </summary>
        public static string Customer_Input_PhoneNumber_PlaceHolder {
            get {
                return ResourceManager.GetString("Customer_Input_PhoneNumber_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản mới ?.
        /// </summary>
        public static string Customer_IsCreateNewAccount {
            get {
                return ResourceManager.GetString("Customer_IsCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao tới địa chỉ khác.
        /// </summary>
        public static string Customer_IsShipToAnother_Address {
            get {
                return ResourceManager.GetString("Customer_IsShipToAnother_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập vào tên !.
        /// </summary>
        public static string Customer_Name_IsRequired {
            get {
                return ResourceManager.GetString("Customer_Name_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ.
        /// </summary>
        public static string Customer_OrderStatus_Cancelled {
            get {
                return ResourceManager.GetString("Customer_OrderStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã giao hàng.
        /// </summary>
        public static string Customer_OrderStatus_Delivered {
            get {
                return ResourceManager.GetString("Customer_OrderStatus_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang giao hàng.
        /// </summary>
        public static string Customer_OrderStatus_Delivering {
            get {
                return ResourceManager.GetString("Customer_OrderStatus_Delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa thanh toán.
        /// </summary>
        public static string Customer_OrderStatus_Ordered {
            get {
                return ResourceManager.GetString("Customer_OrderStatus_Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thanh toán.
        /// </summary>
        public static string Customer_OrderStatus_Paid {
            get {
                return ResourceManager.GetString("Customer_OrderStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuẩn bị.
        /// </summary>
        public static string Customer_OrderStatus_Prepared {
            get {
                return ResourceManager.GetString("Customer_OrderStatus_Prepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả hàng.
        /// </summary>
        public static string Customer_OrderStatus_ReturnedBack {
            get {
                return ResourceManager.GetString("Customer_OrderStatus_ReturnedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Customer_Phone {
            get {
                return ResourceManager.GetString("Customer_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập vào số điện thoại !.
        /// </summary>
        public static string Customer_Phone_IsRequired {
            get {
                return ResourceManager.GetString("Customer_Phone_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Customer_PhoneNumber {
            get {
                return ResourceManager.GetString("Customer_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận.
        /// </summary>
        public static string Customer_Receiver {
            get {
                return ResourceManager.GetString("Customer_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn.
        /// </summary>
        public static string Customer_ThankYou {
            get {
                return ResourceManager.GetString("Customer_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của bạn đã được lưu lại.
        ///Chúng tôi sẽ tìm liên hệ với bạn trong thời gian sớm nhất.
        /// </summary>
        public static string Customer_Your_Information_Saved {
            get {
                return ResourceManager.GetString("Customer_Your_Information_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo link bài cảm nhận khách hàng.
        /// </summary>
        public static string CustomerComment_CreateNew_CustomerComment {
            get {
                return ResourceManager.GetString("CustomerComment_CreateNew_CustomerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gợi ý.
        /// </summary>
        public static string CustomerComment_Hint {
            get {
                return ResourceManager.GetString("CustomerComment_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string CustomerComment_ImagePreview {
            get {
                return ResourceManager.GetString("CustomerComment_ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string CustomerComment_Label {
            get {
                return ResourceManager.GetString("CustomerComment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string CustomerComment_Link {
            get {
                return ResourceManager.GetString("CustomerComment_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string CustomerComment_Name {
            get {
                return ResourceManager.GetString("CustomerComment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm bài cảm nhận khách hàng nào ?.
        /// </summary>
        public static string CustomerComment_Search_Placeholder {
            get {
                return ResourceManager.GetString("CustomerComment_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình ảnh.
        /// </summary>
        public static string CustomerComment_Select_ImagePreview {
            get {
                return ResourceManager.GetString("CustomerComment_Select_ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string CustomerComment_SequenceNumber {
            get {
                return ResourceManager.GetString("CustomerComment_SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bài cảm nhận khách hàng.
        /// </summary>
        public static string CustomerComment_Update_CustomerComment {
            get {
                return ResourceManager.GetString("CustomerComment_Update_CustomerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ với chúng tôi qua {0}.
        /// </summary>
        public static string Error_Page_Message {
            get {
                return ResourceManager.GetString("Error_Page_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lỗi, chúng tôi không tìm thấy trang bạn muốn tới.
        /// </summary>
        public static string Error_Page_NotFound_Message {
            get {
                return ResourceManager.GetString("Error_Page_NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy.
        /// </summary>
        public static string Error_Page_NotFound_Title {
            get {
                return ResourceManager.GetString("Error_Page_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opps, có lỗi xảy ra.
        /// </summary>
        public static string Error_Page_Title {
            get {
                return ResourceManager.GetString("Error_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn chất liệu.
        /// </summary>
        public static string Error_PleaseSelectMaterial {
            get {
                return ResourceManager.GetString("Error_PleaseSelectMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn kích cỡ.
        /// </summary>
        public static string Error_PleaseSelectSize {
            get {
                return ResourceManager.GetString("Error_PleaseSelectSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string Finish_Label {
            get {
                return ResourceManager.GetString("Finish_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân tích mệnh số.
        /// </summary>
        public static string HomePage_AnalysisOfFateContent {
            get {
                return ResourceManager.GetString("HomePage_AnalysisOfFateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sưu tầm các vật phẩm hiếm.
        /// </summary>
        public static string HomePage_CollectRareItemsContent {
            get {
                return ResourceManager.GetString("HomePage_CollectRareItemsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá thêm &gt;.
        /// </summary>
        public static string HomePage_Discover_More {
            get {
                return ResourceManager.GetString("HomePage_Discover_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết kế vật phẩm cá nhân.
        /// </summary>
        public static string HomePage_PersonalizedProductDesignContent {
            get {
                return ResourceManager.GetString("HomePage_PersonalizedProductDesignContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm &gt;.
        /// </summary>
        public static string HomePage_SeeMore {
            get {
                return ResourceManager.GetString("HomePage_SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn để thêm vào vị trí con trỏ.
        /// </summary>
        public static string Knowledge_Click_To_Add_At_Cursor {
            get {
                return ResourceManager.GetString("Knowledge_Click_To_Add_At_Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung bài viết.
        /// </summary>
        public static string Knowledge_Content {
            get {
                return ResourceManager.GetString("Knowledge_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo.
        /// </summary>
        public static string Knowledge_Create {
            get {
                return ResourceManager.GetString("Knowledge_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo bài viết.
        /// </summary>
        public static string Knowledge_CreateNew_Knowledge {
            get {
                return ResourceManager.GetString("Knowledge_CreateNew_Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gợi ý.
        /// </summary>
        public static string Knowledge_Hint {
            get {
                return ResourceManager.GetString("Knowledge_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string Knowledge_ImagePreview {
            get {
                return ResourceManager.GetString("Knowledge_ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Knowledge_Label {
            get {
                return ResourceManager.GetString("Knowledge_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Knowledge_Link {
            get {
                return ResourceManager.GetString("Knowledge_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Knowledge_Name {
            get {
                return ResourceManager.GetString("Knowledge_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem trước.
        /// </summary>
        public static string Knowledge_Preview {
            get {
                return ResourceManager.GetString("Knowledge_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Knowledge_Publish {
            get {
                return ResourceManager.GetString("Knowledge_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm viết nào ?.
        /// </summary>
        public static string Knowledge_Search_Placeholder {
            get {
                return ResourceManager.GetString("Knowledge_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình ảnh để thêm vào bài viết.
        /// </summary>
        public static string Knowledge_Select_ImagePreview {
            get {
                return ResourceManager.GetString("Knowledge_Select_ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình ảnh hiện thị xem trước.
        /// </summary>
        public static string Knowledge_Select_ImagePreview_Public {
            get {
                return ResourceManager.GetString("Knowledge_Select_ImagePreview_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Knowledge_SequenceNumber {
            get {
                return ResourceManager.GetString("Knowledge_SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sơ lược.
        /// </summary>
        public static string Knowledge_Summary {
            get {
                return ResourceManager.GetString("Knowledge_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Knowledge_Update {
            get {
                return ResourceManager.GetString("Knowledge_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bài viết.
        /// </summary>
        public static string Knowledge_Update_Knowledge {
            get {
                return ResourceManager.GetString("Knowledge_Update_Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về chúng tôi.
        /// </summary>
        public static string Label_About_Us {
            get {
                return ResourceManager.GetString("Label_About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tư vấn.
        /// </summary>
        public static string Label_Advising {
            get {
                return ResourceManager.GetString("Label_Advising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch.
        /// </summary>
        public static string Label_Appointments {
            get {
                return ResourceManager.GetString("Label_Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Label_Auth_Login {
            get {
                return ResourceManager.GetString("Label_Auth_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lâm Mộc Bảo.
        /// </summary>
        public static string Label_BranchName {
            get {
                return ResourceManager.GetString("Label_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string Label_Carts {
            get {
                return ResourceManager.GetString("Label_Carts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sản phẩm.
        /// </summary>
        public static string Label_Categories {
            get {
                return ResourceManager.GetString("Label_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn.
        /// </summary>
        public static string Label_Common_PleaseSelectItem {
            get {
                return ResourceManager.GetString("Label_Common_PleaseSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string Label_Complete_Order {
            get {
                return ResourceManager.GetString("Label_Complete_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string Label_Contact {
            get {
                return ResourceManager.GetString("Label_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm nhận khách hàng.
        /// </summary>
        public static string Label_CustomerComments {
            get {
                return ResourceManager.GetString("Label_CustomerComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên gia thiết kế vật phẩm Phong Thủy.
        /// </summary>
        public static string Label_Fengshui_Designer {
            get {
                return ResourceManager.GetString("Label_Fengshui_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Label_Home_Page {
            get {
                return ResourceManager.GetString("Label_Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ bạn quan tâm.
        /// </summary>
        public static string Label_InterestedInService {
            get {
                return ResourceManager.GetString("Label_InterestedInService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiến thức.
        /// </summary>
        public static string Label_Knowledge {
            get {
                return ResourceManager.GetString("Label_Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiến thức.
        /// </summary>
        public static string Label_Knowledges {
            get {
                return ResourceManager.GetString("Label_Knowledges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch.
        /// </summary>
        public static string Label_Make_A_Appointment {
            get {
                return ResourceManager.GetString("Label_Make_A_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất liệu.
        /// </summary>
        public static string Label_Materials {
            get {
                return ResourceManager.GetString("Label_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link bài báo.
        /// </summary>
        public static string Label_NewsPaperPosts {
            get {
                return ResourceManager.GetString("Label_NewsPaperPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn đặt hàng.
        /// </summary>
        public static string Label_Orders {
            get {
                return ResourceManager.GetString("Label_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thanh toán.
        /// </summary>
        public static string Label_PaymentInfos {
            get {
                return ResourceManager.GetString("Label_PaymentInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string Label_Payments {
            get {
                return ResourceManager.GetString("Label_Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật phẩm.
        /// </summary>
        public static string Label_Products {
            get {
                return ResourceManager.GetString("Label_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngũ hành.
        /// </summary>
        public static string Label_ProductTypes {
            get {
                return ResourceManager.GetString("Label_ProductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi.
        /// </summary>
        public static string Label_Promotions {
            get {
                return ResourceManager.GetString("Label_Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích cỡ.
        /// </summary>
        public static string Label_Sizes {
            get {
                return ResourceManager.GetString("Label_Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        public static string Label_Stocks {
            get {
                return ResourceManager.GetString("Label_Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt hệ thống.
        /// </summary>
        public static string Label_SystemSettings {
            get {
                return ResourceManager.GetString("Label_SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Label_Tags {
            get {
                return ResourceManager.GetString("Label_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag thuộc ngũ hành (bộ lọc trang sản phẩm).
        /// </summary>
        public static string Label_Tags_By_ProductTypes {
            get {
                return ResourceManager.GetString("Label_Tags_By_ProductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Label_User_Registers {
            get {
                return ResourceManager.GetString("Label_User_Registers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng của bạn.
        /// </summary>
        public static string Label_YourOrder {
            get {
                return ResourceManager.GetString("Label_YourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string Login_Button_ForgetPassword {
            get {
                return ResourceManager.GetString("Login_Button_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Button_Login {
            get {
                return ResourceManager.GetString("Login_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Login_Label_Password {
            get {
                return ResourceManager.GetString("Login_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Login_Label_Username {
            get {
                return ResourceManager.GetString("Login_Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần đăng nhập để thực hiện tính năng này.
        /// </summary>
        public static string Login_Title_Consider_Login {
            get {
                return ResourceManager.GetString("Login_Title_Consider_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản hoặc mật khẩu không khớp !.
        /// </summary>
        public static string Login_Username_Password_Mismatch {
            get {
                return ResourceManager.GetString("Login_Username_Password_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo chất liệu.
        /// </summary>
        public static string Material_CreateNew_Material {
            get {
                return ResourceManager.GetString("Material_CreateNew_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Material_Delete_Confirm {
            get {
                return ResourceManager.GetString("Material_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Material_Description {
            get {
                return ResourceManager.GetString("Material_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Material_Name {
            get {
                return ResourceManager.GetString("Material_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm chất liệu nào ?.
        /// </summary>
        public static string Material_Search_Placeholder {
            get {
                return ResourceManager.GetString("Material_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chất liệu.
        /// </summary>
        public static string Material_Update_Material {
            get {
                return ResourceManager.GetString("Material_Update_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo link bài báo.
        /// </summary>
        public static string NewsPaperPost_CreateNew_NewsPaperPost {
            get {
                return ResourceManager.GetString("NewsPaperPost_CreateNew_NewsPaperPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gợi ý.
        /// </summary>
        public static string NewsPaperPost_Hint {
            get {
                return ResourceManager.GetString("NewsPaperPost_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string NewsPaperPost_ImagePreview {
            get {
                return ResourceManager.GetString("NewsPaperPost_ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string NewsPaperPost_Label {
            get {
                return ResourceManager.GetString("NewsPaperPost_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string NewsPaperPost_Link {
            get {
                return ResourceManager.GetString("NewsPaperPost_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string NewsPaperPost_Name {
            get {
                return ResourceManager.GetString("NewsPaperPost_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm link bài bào nào ?.
        /// </summary>
        public static string NewsPaperPost_Search_Placeholder {
            get {
                return ResourceManager.GetString("NewsPaperPost_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình ảnh.
        /// </summary>
        public static string NewsPaperPost_Select_ImagePreview {
            get {
                return ResourceManager.GetString("NewsPaperPost_Select_ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string NewsPaperPost_SequenceNumber {
            get {
                return ResourceManager.GetString("NewsPaperPost_SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật link bài viết.
        /// </summary>
        public static string NewsPaperPost_Update_NewsPaperPost {
            get {
                return ResourceManager.GetString("NewsPaperPost_Update_NewsPaperPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn quận/ huyện.
        /// </summary>
        public static string Order_Address_Please_Input_District {
            get {
                return ResourceManager.GetString("Order_Address_Please_Input_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập vào địa chỉ email.
        /// </summary>
        public static string Order_Address_Please_Input_Email {
            get {
                return ResourceManager.GetString("Order_Address_Please_Input_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập vào tên.
        /// </summary>
        public static string Order_Address_Please_Input_FullName {
            get {
                return ResourceManager.GetString("Order_Address_Please_Input_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập vào số điện thoại.
        /// </summary>
        public static string Order_Address_Please_Input_PhoneNumber {
            get {
                return ResourceManager.GetString("Order_Address_Please_Input_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tỉnh/ thành phố.
        /// </summary>
        public static string Order_Address_Please_Input_Province {
            get {
                return ResourceManager.GetString("Order_Address_Please_Input_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn phường/ xã.
        /// </summary>
        public static string Order_Address_Please_Input_Ward {
            get {
                return ResourceManager.GetString("Order_Address_Please_Input_Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách hậu mãi.
        /// </summary>
        public static string Order_After_Sell_Policy {
            get {
                return ResourceManager.GetString("Order_After_Sell_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string Order_Customer_Contact_Infos {
            get {
                return ResourceManager.GetString("Order_Customer_Contact_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin khách hàng.
        /// </summary>
        public static string Order_Customer_Infos {
            get {
                return ResourceManager.GetString("Order_Customer_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string Order_Customer_Name {
            get {
                return ResourceManager.GetString("Order_Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giao hàng.
        /// </summary>
        public static string Order_Delivery_Infos {
            get {
                return ResourceManager.GetString("Order_Delivery_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đơn hàng.
        /// </summary>
        public static string Order_Infos {
            get {
                return ResourceManager.GetString("Order_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng và bảo quản chuỗi.
        /// </summary>
        public static string Order_Instructions_for_use_and_Maintenance {
            get {
                return ResourceManager.GetString("Order_Instructions_for_use_and_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển trạng thái.
        /// </summary>
        public static string Order_Move_To_Status {
            get {
                return ResourceManager.GetString("Order_Move_To_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Order_Note {
            get {
                return ResourceManager.GetString("Order_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string Order_Promotion_None {
            get {
                return ResourceManager.GetString("Order_Promotion_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm đơn đặt hàng.
        /// </summary>
        public static string Order_Search_Placeholder {
            get {
                return ResourceManager.GetString("Order_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Order_Status {
            get {
                return ResourceManager.GetString("Order_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc mừng bạn đã đặt hàng thành công.
        /// </summary>
        public static string Order_Success_Label {
            get {
                return ResourceManager.GetString("Order_Success_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem đơn đặt hàng.
        /// </summary>
        public static string Order_View_Order {
            get {
                return ResourceManager.GetString("Order_View_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách bảo hành và đổi trả.
        /// </summary>
        public static string Order_Warranty_And_Return_Policy {
            get {
                return ResourceManager.GetString("Order_Warranty_And_Return_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string Paid_Label {
            get {
                return ResourceManager.GetString("Paid_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung chuyển khoản: Số điện thoại đặt hàng.
        /// </summary>
        public static string Payment_Content {
            get {
                return ResourceManager.GetString("Payment_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển khoản ngân hàng.
        /// </summary>
        public static string Payment_Method_BankTransfer {
            get {
                return ResourceManager.GetString("Payment_Method_BankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán khi nhận hàng (COD).
        /// </summary>
        public static string Payment_Method_COD {
            get {
                return ResourceManager.GetString("Payment_Method_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ hàng.
        /// </summary>
        public static string Product_AddToCart {
            get {
                return ResourceManager.GetString("Product_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục xem sản phẩm.
        /// </summary>
        public static string Product_Back_Product_Page {
            get {
                return ResourceManager.GetString("Product_Back_Product_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string Product_CalculatedPrice_Total {
            get {
                return ResourceManager.GetString("Product_CalculatedPrice_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string Product_Cart_Pay {
            get {
                return ResourceManager.GetString("Product_Cart_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật giỏ hàng.
        /// </summary>
        public static string Product_Cart_UpdateCart {
            get {
                return ResourceManager.GetString("Product_Cart_UpdateCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng giỏ hàng.
        /// </summary>
        public static string Product_Carts_Sum {
            get {
                return ResourceManager.GetString("Product_Carts_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình ảnh cho sản phẩm.
        /// </summary>
        public static string Product_Choose_Files {
            get {
                return ResourceManager.GetString("Product_Choose_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string Product_CreatedAt {
            get {
                return ResourceManager.GetString("Product_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo sản phẩm mới.
        /// </summary>
        public static string Product_CreateNew_Product {
            get {
                return ResourceManager.GetString("Product_CreateNew_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh hiện tại.
        /// </summary>
        public static string Product_CurrentImages {
            get {
                return ResourceManager.GetString("Product_CurrentImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao hàng.
        /// </summary>
        public static string Product_Delivery_Fee {
            get {
                return ResourceManager.GetString("Product_Delivery_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí với các đơn hàng trên 200,000 ₫.
        /// </summary>
        public static string Product_Delivery_Fee_Content {
            get {
                return ResourceManager.GetString("Product_Delivery_Fee_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết.
        /// </summary>
        public static string Product_Description {
            get {
                return ResourceManager.GetString("Product_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Product_Detail {
            get {
                return ResourceManager.GetString("Product_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin sản phẩm.
        /// </summary>
        public static string Product_Details {
            get {
                return ResourceManager.GetString("Product_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất.
        /// </summary>
        public static string Product_Export_Stock {
            get {
                return ResourceManager.GetString("Product_Export_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất xứ.
        /// </summary>
        public static string Product_From {
            get {
                return ResourceManager.GetString("Product_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string Product_Images {
            get {
                return ResourceManager.GetString("Product_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập.
        /// </summary>
        public static string Product_Import_Stock {
            get {
                return ResourceManager.GetString("Product_Import_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string Product_Infomation {
            get {
                return ResourceManager.GetString("Product_Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan tâm.
        /// </summary>
        public static string Product_InterestedIn {
            get {
                return ResourceManager.GetString("Product_InterestedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất liệu.
        /// </summary>
        public static string Product_Material {
            get {
                return ResourceManager.GetString("Product_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh mới.
        /// </summary>
        public static string Product_NewImages {
            get {
                return ResourceManager.GetString("Product_NewImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có vẻ như không có sản phẩm nào ở đây cả...
        /// </summary>
        public static string Product_No_Result {
            get {
                return ResourceManager.GetString("Product_No_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        public static string Product_Order {
            get {
                return ResourceManager.GetString("Product_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string Product_ProductName {
            get {
                return ResourceManager.GetString("Product_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ưu đãi.
        /// </summary>
        public static string Product_Promotion_Code {
            get {
                return ResourceManager.GetString("Product_Promotion_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giảm giá không hết hạn.
        /// </summary>
        public static string Product_Promotion_Expired {
            get {
                return ResourceManager.GetString("Product_Promotion_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giảm giá không tồn tại.
        /// </summary>
        public static string Product_Promotion_Invalid {
            get {
                return ResourceManager.GetString("Product_Promotion_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm {0}% : {1}.
        /// </summary>
        public static string Product_Promotion_Percent {
            get {
                return ResourceManager.GetString("Product_Promotion_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá mua.
        /// </summary>
        public static string Product_PurchasingPrice {
            get {
                return ResourceManager.GetString("Product_PurchasingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string Product_Quantity {
            get {
                return ResourceManager.GetString("Product_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm sản phẩm nào ?.
        /// </summary>
        public static string Product_Search_Placeholder {
            get {
                return ResourceManager.GetString("Product_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán.
        /// </summary>
        public static string Product_SellingPrice {
            get {
                return ResourceManager.GetString("Product_SellingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size hạt.
        /// </summary>
        public static string Product_Size_Necklace {
            get {
                return ResourceManager.GetString("Product_Size_Necklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Product_Summary {
            get {
                return ResourceManager.GetString("Product_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm tính.
        /// </summary>
        public static string Product_Temp_Sum_Price {
            get {
                return ResourceManager.GetString("Product_Temp_Sum_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật sản phẩm.
        /// </summary>
        public static string Product_Update_Product {
            get {
                return ResourceManager.GetString("Product_Update_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo loại sản phẩm mới.
        /// </summary>
        public static string ProductType_CreateNew_ProductType {
            get {
                return ResourceManager.GetString("ProductType_CreateNew_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string ProductType_Name {
            get {
                return ResourceManager.GetString("ProductType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm ngũ hành nào ?.
        /// </summary>
        public static string ProductType_Search_Placeholder {
            get {
                return ResourceManager.GetString("ProductType_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string ProductType_SequenceNumber {
            get {
                return ResourceManager.GetString("ProductType_SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách cấp con.
        /// </summary>
        public static string ProductType_SubTypes {
            get {
                return ResourceManager.GetString("ProductType_SubTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách cấp con (cách nhau bằng dấu phẩy).
        /// </summary>
        public static string ProductType_SubTypes_Hint {
            get {
                return ResourceManager.GetString("ProductType_SubTypes_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật ngũ hành.
        /// </summary>
        public static string ProductType_Update_ProductType {
            get {
                return ResourceManager.GetString("ProductType_Update_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chắc chắn muốn xóa {0} ?.
        /// </summary>
        public static string Produuct_Delete_Confirm {
            get {
                return ResourceManager.GetString("Produuct_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khuyến mãi.
        /// </summary>
        public static string Promotion_Code {
            get {
                return ResourceManager.GetString("Promotion_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt.
        /// </summary>
        public static string Promotion_Content {
            get {
                return ResourceManager.GetString("Promotion_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo khuyến mãi mới.
        /// </summary>
        public static string Promotion_CreateNew_Promotion {
            get {
                return ResourceManager.GetString("Promotion_CreateNew_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần trăm giảm giá.
        /// </summary>
        public static string Promotion_DiscountPercent {
            get {
                return ResourceManager.GetString("Promotion_DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        public static string Promotion_From {
            get {
                return ResourceManager.GetString("Promotion_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có hiệu lực.
        /// </summary>
        public static string Promotion_IsActive {
            get {
                return ResourceManager.GetString("Promotion_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thủ công.
        /// </summary>
        public static string Promotion_Manual {
            get {
                return ResourceManager.GetString("Promotion_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chế độ.
        /// </summary>
        public static string Promotion_Mode {
            get {
                return ResourceManager.GetString("Promotion_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo thời gian.
        /// </summary>
        public static string Promotion_Period {
            get {
                return ResourceManager.GetString("Promotion_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm mã khuyến mãi nào ?.
        /// </summary>
        public static string Promotion_Search_Placeholder {
            get {
                return ResourceManager.GetString("Promotion_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc.
        /// </summary>
        public static string Promotion_To {
            get {
                return ResourceManager.GetString("Promotion_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật khuyến mãi.
        /// </summary>
        public static string Promotion_Update_Promotion {
            get {
                return ResourceManager.GetString("Promotion_Update_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register_Button_Register {
            get {
                return ResourceManager.GetString("Register_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Register_Label_Email {
            get {
                return ResourceManager.GetString("Register_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Register_Label_Password {
            get {
                return ResourceManager.GetString("Register_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string Register_Label_RetypePassword {
            get {
                return ResourceManager.GetString("Register_Label_RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Register_Label_Username {
            get {
                return ResourceManager.GetString("Register_Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thiết kế vật phẩm cá nhân.
        /// </summary>
        public static string Register_Product_Design {
            get {
                return ResourceManager.GetString("Register_Product_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không khớp.
        /// </summary>
        public static string Register_RetypePassword_Mismatch {
            get {
                return ResourceManager.GetString("Register_RetypePassword_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới tài khoản.
        /// </summary>
        public static string Register_Title_Create_Account {
            get {
                return ResourceManager.GetString("Register_Title_Create_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã tồn tại.
        /// </summary>
        public static string Register_Username_Is_Existing {
            get {
                return ResourceManager.GetString("Register_Username_Is_Existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại trang chủ.
        /// </summary>
        public static string Return_Back_Homepage {
            get {
                return ResourceManager.GetString("Return_Back_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo kích cỡ.
        /// </summary>
        public static string Size_CreateNew_Size {
            get {
                return ResourceManager.GetString("Size_CreateNew_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Size_Name {
            get {
                return ResourceManager.GetString("Size_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số.
        /// </summary>
        public static string Size_Number {
            get {
                return ResourceManager.GetString("Size_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm thông tin kích cỡ nào ?.
        /// </summary>
        public static string Size_Search_Placeholder {
            get {
                return ResourceManager.GetString("Size_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string Size_Unit {
            get {
                return ResourceManager.GetString("Size_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật kích cỡ.
        /// </summary>
        public static string Size_Update_Size {
            get {
                return ResourceManager.GetString("Size_Update_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật kích cỡ.
        /// </summary>
        public static string Size_Update_Tag {
            get {
                return ResourceManager.GetString("Size_Update_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc theo giá.
        /// </summary>
        public static string Sort_By_Price {
            get {
                return ResourceManager.GetString("Sort_By_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Còn lại  {0} sản phẩm.
        /// </summary>
        public static string Stock_Message_Show_Quantity {
            get {
                return ResourceManager.GetString("Stock_Message_Show_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã bán - có thể đặt làm lại.
        /// </summary>
        public static string Stock_Message_Show_Rare_Can_Order_To_Create {
            get {
                return ResourceManager.GetString("Stock_Message_Show_Rare_Can_Order_To_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ còn lại {0} sản phẩm.
        /// </summary>
        public static string Stock_Message_Show_Rare_Quantity {
            get {
                return ResourceManager.GetString("Stock_Message_Show_Rare_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string SystemSetting_BankAccount {
            get {
                return ResourceManager.GetString("SystemSetting_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string SystemSetting_BankName {
            get {
                return ResourceManager.GetString("SystemSetting_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ tài khoản.
        /// </summary>
        public static string SystemSetting_CardHolderName {
            get {
                return ResourceManager.GetString("SystemSetting_CardHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ liên lạc.
        /// </summary>
        public static string SystemSetting_ContactAddress {
            get {
                return ResourceManager.GetString("SystemSetting_ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại liên lạc.
        /// </summary>
        public static string SystemSetting_ContactPhoneNumbers {
            get {
                return ResourceManager.GetString("SystemSetting_ContactPhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email liên hệ.
        /// </summary>
        public static string SystemSetting_Email {
            get {
                return ResourceManager.GetString("SystemSetting_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string SystemSetting_Facebook {
            get {
                return ResourceManager.GetString("SystemSetting_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google map.
        /// </summary>
        public static string SystemSetting_GoogleMapFrameUrl {
            get {
                return ResourceManager.GetString("SystemSetting_GoogleMapFrameUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nổi bật bài viết/ sản phẩm trong số ngày.
        /// </summary>
        public static string SystemSetting_HighlightItemsInDays {
            get {
                return ResourceManager.GetString("SystemSetting_HighlightItemsInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string SystemSetting_Instagram {
            get {
                return ResourceManager.GetString("SystemSetting_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ tài khoản momo.
        /// </summary>
        public static string SystemSetting_MomoPaymentCardHolder {
            get {
                return ResourceManager.GetString("SystemSetting_MomoPaymentCardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại momo.
        /// </summary>
        public static string SystemSetting_MomoPaymentPhoneNumber {
            get {
                return ResourceManager.GetString("SystemSetting_MomoPaymentPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momo QR Code.
        /// </summary>
        public static string SystemSetting_MomoPaymentQRImage {
            get {
                return ResourceManager.GetString("SystemSetting_MomoPaymentQRImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng bài viết/ sản phẩm được nổi bật.
        /// </summary>
        public static string SystemSetting_NumberOfHighlightItems {
            get {
                return ResourceManager.GetString("SystemSetting_NumberOfHighlightItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại liên hệ.
        /// </summary>
        public static string SystemSetting_PhoneNumber {
            get {
                return ResourceManager.GetString("SystemSetting_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình ảnh.
        /// </summary>
        public static string SystemSetting_Select_Images {
            get {
                return ResourceManager.GetString("SystemSetting_Select_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm việc.
        /// </summary>
        public static string SystemSetting_WorkingTime {
            get {
                return ResourceManager.GetString("SystemSetting_WorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string SystemSetting_Youtube {
            get {
                return ResourceManager.GetString("SystemSetting_Youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tag mới.
        /// </summary>
        public static string Tag_CreateNew_Tag {
            get {
                return ResourceManager.GetString("Tag_CreateNew_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Tag_Label {
            get {
                return ResourceManager.GetString("Tag_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Tag_Name {
            get {
                return ResourceManager.GetString("Tag_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn tìm tag nào ?.
        /// </summary>
        public static string Tag_Search_Placeholder {
            get {
                return ResourceManager.GetString("Tag_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tag.
        /// </summary>
        public static string Tag_Update_Tag {
            get {
                return ResourceManager.GetString("Tag_Update_Tag", resourceCulture);
            }
        }
    }
}
